services:
  fhir-validator:
    build:
      context: .
      # Use default platform or override with DOCKER_DEFAULT_PLATFORM env var
    ports:
      - "${FV_SERVER_PORT:-8880}:8880"
      - "5432:5432"
    environment:
      - PG_HOST=127.0.0.1
#    depends_on:
#      postgres:
#        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FV_SERVER_PORT:-8880}/health"]
      interval: 30s
      start_period: 40s
      timeout: 3s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
    - fhir-validator
    - postgres-exporter

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@fhir-validator:5432/fhir_validator?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      fhir-validator:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4:9.4.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - fhir-validator
    restart: unless-stopped

volumes:
  pgadmin-data: